#!/bin/bash
git submodule update --init --recursive
(cd boggart && pip install .)
(cd kaskara && pip install . && docker build -t squareslab/kaskara .)
(cd darjeeling && pip install .)
(cd dronekit && pip install .)
(cd start_core && pip install .)
(cd start_image && pip install .)
(cd start_dbi && pip install .)
(cd start_repair && pip install .)
(cd start_cli && pip install .)
docker build -t christimperley/start:stack .
