#!/bin/bash
git submodule update --init --recursive
(pip3 install --upgrade bugzoo==2.1.16)
(cd boggart && pip3 install --upgrade .)
(cd kaskara && pip3 install --upgrade .)
(cd darjeeling && pip3 install --upgrade .)
(cd start_core && pip3 install --upgrade .)
(cd start_image && pip3 install --upgrade .)
(cd start_dbi && pip3 install --upgrade .)
(cd start_repair && pip3 install --upgrade .)
(cd start_cli && pip3 install --upgrade .)
