#!/bin/bash
(cd kaskara && pip install .)
(cd dronekit && pip install .)
(cd start_core && pip install .)
(cd start_image && pip install .)
(cd start_dbi && pip install .)
(cd start_repair && pip install .)
(cd start_cli && pip install .)
docker build -t christimperley/start:stack .
